const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#00B5A5",
    background: "#F5F7FA",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#00B5A5",
    primaryForeground: "#FFFFFF",
    secondary: "#1A3A52",
    secondaryForeground: "#FFFFFF",
    muted: "#F0F4F8",
    mutedForeground: "#757575",
    accent: "#E8EDF2",
    accentForeground: "#1A1A1A",
    destructive: "#E53935",
    destructiveForeground: "#FFFFFF",
    border: "#E0E6ED",
    input: "#E0E6ED",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00B5A5",
    background: "#121212",
    foreground: "#FFFFFF",
    card: "#1E1E1E",
    cardForeground: "#FFFFFF",
    primary: "#00B5A5",
    primaryForeground: "#FFFFFF",
    secondary: "#1A3A52",
    secondaryForeground: "#FFFFFF",
    muted: "#252525",
    mutedForeground: "#B0B0B0",
    accent: "#2D2D2D",
    accentForeground: "#FFFFFF",
    destructive: "#E53935",
    destructiveForeground: "#FFFFFF",
    border: "#333333",
    input: "#333333",
  },
  radius: 12,
};

export default colors;
